version: '0.1'
name: vault-provider-examples

services:
  vault:
    image: vault:latest
    container_name: vault-server
    ports:
      - "8200:8200"
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://localhost:8200
    networks:
      vault-provider-examples:

  mysql:
    image: mysql:8.0.33
    container_name: vault-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password01
      MYSQL_DATABASE: vault-examples
      MYSQL_USER: vault-user
      MYSQL_PASSWORD: vault-password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose-setup/database:/docker-entrypoint-initdb.d
    networks:
      vault-provider-examples:

networks:
  vault-provider-examples:
    driver: bridge
